#@ load("@ytt:data", "data")
---
profile: full
ceip_policy_disclosed: true # Installation fails if this is not set to true. Not a string.
buildservice:
  # "eu.gcr.io/sdezitter-labs/build-service"
  kp_default_repository: #@ "{}/{}/build-service".format(data.values.container_registry.hostname,data.values.container_registry.project) 
  kp_default_repository_username: #@ data.values.container_registry.username
  kp_default_repository_password: #@ data.values.container_registry.password
  tanzunet_username: #@ data.values.tanzunet.username
  tanzunet_password: #@ data.values.tanzunet.password
  enable_automatic_dependency_updates: true
  descriptor_name: full

supply_chain: testing_scanning

cnrs:
  domain_name: #@ "cnr.{}".format(data.values.ingress.domain)
  domain_template: "{{.Name}}-{{.Namespace}}.{{.Domain}}"
  default_tls_secret: #@ "{}/cnr-{}".format(data.values.ingress.contour_tls_namespace,data.values.ingress.contour_tls_secret)

ootb_supply_chain_testing_scanning:
  registry:
    server: #@ data.values.container_registry.hostname
    repository: #@ "{}/{}".format(data.values.container_registry.project,data.values.container_registry.project_workload)
  gitops:
    ssh_secret: ""

learningcenter:
  ingressDomain: #@ "learning-center.{}".format(data.values.ingress.domain)
  ingressSecret:
    secretName: #@ "learning-center-{}".format(data.values.ingress.contour_tls_secret)

contour:
  envoy:
    service:
      annotations:      
        external-dns.alpha.kubernetes.io/hostname: #@ "*.{}".format(data.values.ingress.domain)
      type: LoadBalancer

accelerator: 
  domain: #@ "{}".format(data.values.ingress.domain)                         
  ingress:
    include: true
  tls:
    secretName: #@ data.values.ingress.contour_tls_secret                                                 
    namespace: #@ data.values.ingress.contour_tls_namespace
  server:
    service_type: ClusterIP

tap_gui:
  service_type: ClusterIP
  ingressEnabled: "true"
  ingressDomain: #@ data.values.ingress.domain
  app_config:
    app:
      baseUrl: #@ "http://tap-gui.{}".format(data.values.ingress.domain)
    integrations:
      github: # Other are integrations available
        - host: github.com
          token: #@ data.values.tap_gui.github_token
    catalog:
      locations:
        - type: url
          target: https://github.com/SteveDZ/tap-gui/blob/main/catalog-info.yaml
    backend:
      baseUrl: #@ "http://tap-gui.{}".format(data.values.ingress.domain)
      cors:
        origin: #@ "http://tap-gui.{}".format(data.values.ingress.domain)

metadata_store:
  app_service_type: ClusterIP # (optional) Defaults to LoadBalancer. Change to NodePort for distributions that don't support LoadBalancer

grype:
  namespace: #@ data.values.developer_namespace
  targetImagePullSecret: registry-credentials